### ISSUE TITLE
无法安装包

### ISSUE THREAD

**Issue by wangyiwu** [RT-Thread-packages/paho-mqtt#53]
我使用 adminconfig 命令安装，但在输入命令后：pkgs --update 我得到错误:

```
$ pkgs --update
Traceback (most recent call last):
  File "D:\RT-ThreadStudio\platform\env_released\env\tools\ConEmu\ConEmu\..\..\..\tools\scripts\env.py", line 126, in <module>
    main()
  File "D:\RT-ThreadStudio\platform\env_released\env\tools\ConEmu\ConEmu\..\..\..\tools\scripts\env.py", line 122, in main
    args.func(args)
  File "D:\RT-ThreadStudio\platform\env_released\env\tools\scripts\cmds\cmd_package\__init__.py", line 41, in run_env_cmd
    package_update()
  File "D:\RT-ThreadStudio\platform\env_released\env\tools\scripts\cmds\cmd_package\cmd_package_update.py", line 842, in package_update
    if not install_packages(sys_value, force_update):
  File "D:\RT-ThreadStudio\platform\env_released\env\tools\scripts\cmds\cmd_package\cmd_package_update.py", line 792, in install_packages
    if install_package(env_root, pkgs_root, bsp_root, package, force_update):
  File "D:\RT-ThreadStudio\platform\env_released\env\tools\scripts\cmds\cmd_package\cmd_package_update.py", line 267, in install_package
    url_from_json = package.get_url(package_info['ver'])
KeyError: 'ver'
```

**Comment by wangyiwu** [comment]
I fixed this using RT Thread Setting instead of using command line

**Comment by GarMingLi** [comment]
我也是遇到同样的问题
